In [17]:
import pandas as pd
import sklearn as sk
from sklearn import linear_model
import geopy
from geopy import distance
data = pd.read_csv("uber.csv")
print(data.head(5))
data.dropna()

   Unnamed: 0                            key  fare_amount  \
0    24238194    2015-05-07 19:52:06.0000003          7.5   
1    27835199    2009-07-17 20:04:56.0000002          7.7   
2    44984355   2009-08-24 21:45:00.00000061         12.9   
3    25894730    2009-06-26 08:22:21.0000001          5.3   
4    17610152  2014-08-28 17:47:00.000000188         16.0   

           pickup_datetime  pickup_longitude  pickup_latitude  \
0  2015-05-07 19:52:06 UTC        -73.999817        40.738354   
1  2009-07-17 20:04:56 UTC        -73.994355        40.728225   
2  2009-08-24 21:45:00 UTC        -74.005043        40.740770   
3  2009-06-26 08:22:21 UTC        -73.976124        40.790844   
4  2014-08-28 17:47:00 UTC        -73.925023        40.744085   

   dropoff_longitude  dropoff_latitude  passenger_count  
0         -73.999512         40.723217                1  
1         -73.994710         40.750325                1  
2         -73.962565         40.772647                1  
3         

Unnamed: 0                            key  fare_amount  \
0         24238194    2015-05-07 19:52:06.0000003          7.5   
1         27835199    2009-07-17 20:04:56.0000002          7.7   
2         44984355   2009-08-24 21:45:00.00000061         12.9   
3         25894730    2009-06-26 08:22:21.0000001          5.3   
4         17610152  2014-08-28 17:47:00.000000188         16.0   
...            ...                            ...          ...   
199995    42598914   2012-10-28 10:49:00.00000053          3.0   
199996    16382965    2014-03-14 01:09:00.0000008          7.5   
199997    27804658   2009-06-29 00:42:00.00000078         30.9   
199998    20259894    2015-05-20 14:56:25.0000004         14.5   
199999    11951496   2010-05-15 04:08:00.00000076         14.1   

                pickup_datetime  pickup_longitude  pickup_latitude  \
0       2015-05-07 19:52:06 UTC        -73.999817        40.738354   
1       2009-07-17 20:04:56 UTC        -73.994355        40.728225   
2       2009-08-24 21:45:00 UTC        -74.005043        40.740770   
3       2009-06-26 08:22:21 UTC        -73.976124        40.790844   
4       2014-08-28 17:47:00 UTC        -73.925023        40.744085   
...                         ...               ...              ...   
199995  2012-10-28 10:49:00 UTC        -73.987042        40.739367   
199996  2014-03-14 01:09:00 UTC        -73.984722        40.736837   
199997  2009-06-29 00:42:00 UTC        -73.986017        40.756487   
199998  2015-05-20 14:56:25 UTC        -73.997124        40.725452   
199999  2010-05-15 04:08:00 UTC        -73.984395        40.720077   

        dropoff_longitude  dropoff_latitude  passenger_count  
0              -73.999512         40.723217                1  
1              -73.994710         40.750325                1  
2              -73.962565         40.772647                1  
3              -73.965316         40.803349                3  
4              -73.973082         40.761247                5  
...                   ...               ...              ...  
199995         -73.986525         40.740297                1  
199996         -74.006672         40.739620                1  
199997         -73.858957         40.692588                2  
199998         -73.983215         40.695415                1  
199999         -73.985508         40.768793                1  

[199999 rows x 9 columns]

In [255]:
distanceList = []
timeList = []
for (index, row) in data.iterrows():
    tempDistance = 0
    if -90 <= data.loc[index, 'pickup_latitude'] <= 90 and -90 <= data.loc[index, 'dropoff_latitude'] <= 90:
        pickup = (data.loc[index, 'pickup_latitude'], data.loc[index, 'pickup_longitude'])
        dropOff = (data.loc[index, 'dropoff_latitude'], data.loc[index, 'dropoff_longitude'])
        tempDistance = distance.distance(pickup, dropOff).miles
    distanceList.append(tempDistance)
    
    tempTime = data.loc[index, 'pickup_datetime']
    tempTime = tempTime[:19]
    tempTime = dt.datetime.fromisoformat(tempTime)
    tempTime = float(tempTime.strftime('%H%M%S'))
    timeList.append(tempTime)

data['distance'] = distanceList
data['pickup_time'] = timeList

print(data.head(5))
data.info()

   Unnamed: 0                            key  fare_amount  \
0    24238194    2015-05-07 19:52:06.0000003          7.5   
1    27835199    2009-07-17 20:04:56.0000002          7.7   
2    44984355   2009-08-24 21:45:00.00000061         12.9   
3    25894730    2009-06-26 08:22:21.0000001          5.3   
4    17610152  2014-08-28 17:47:00.000000188         16.0   

           pickup_datetime  pickup_longitude  pickup_latitude  \
0  2015-05-07 19:52:06 UTC        -73.999817        40.738354   
1  2009-07-17 20:04:56 UTC        -73.994355        40.728225   
2  2009-08-24 21:45:00 UTC        -74.005043        40.740770   
3  2009-06-26 08:22:21 UTC        -73.976124        40.790844   
4  2014-08-28 17:47:00 UTC        -73.925023        40.744085   

   dropoff_longitude  dropoff_latitude  passenger_count  distance  pickup_time  
0         -73.999512         40.723217                1  1.044594     195206.0  
1         -73.994710         40.750325                1  1.525071     200456.0  

In [277]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.multiclass import OneVsOneClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.model_selection import GridSearchCV

df = pd.DataFrame(data, columns = ['distance', 'fare_amount'])
array = df.to_numpy()
y = data[["fare_amount"]]
x = data[['distance', 'pickup_time']]

print(array)

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 0)
# xtrain = xtrain.reshape(-1, 1)
# ytrain = ytrain.reshape(-1, 1)
# xtest = xtest.reshape(-1, 1)
# ytest = ytest.reshape(-1, 1)

regressor = LinearRegression()
regressor.fit(xtrain, ytrain)

y_pred = regressor.predict(xtest)
   
print("Predicted Results: ")
print(y_pred)
mse = sklearn.metrics.mean_squared_error(ytest.astype(int), y_pred.astype(int))
print("MSE: ", mse)
cmatrix = metrics.confusion_matrix(ytest.astype(int), y_pred.astype(int))
print(cmatrix)

log_regression = LogisticRegression()
log_regression.fit(xtrain.astype(int),ytrain.astype(int))

y_pred_proba = log_regression.predict_proba(xtest.astype(int))[::,1]
fpr, tpr = metrics.roc_curve(ytest.astype(int),  y_pred_proba, pos_label='Label')

plt.plot(fpr,tpr)
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

[[ 1.04459379  7.5       ]
 [ 1.52507061  7.7       ]
 [ 3.13146393 12.9       ]
 ...
 [ 7.99575236 30.9       ]
 [ 2.19751177 14.5       ]
 [ 3.36203965 14.1       ]]
Predicted Results: 
[[11.15446972]
 [11.73805165]
 [11.32241726]
 ...
 [11.46275431]
 [11.57664264]
 [11.323759  ]]
MSE:  105.056125
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


C:\Users\brand\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\brand\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\brand\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:572: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  y_true = (y_true == pos_label)

TypeError: 'bool' object is not subscriptable

In [220]:
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(ytrain, xtrain)

pred = regressor.predict([[]])
print(pred)

[7.]


In [157]:
import datetime as dt
temp = data.loc[0, 'pickup_datetime']
#tempTime = dt.time.fromisoformat(temp)
temp = temp[11:19]
print(temp)
tempTime = dt.time.fromisoformat(temp)
print(tempTime)

19:52:06
19:52:06


In [227]:
from sklearn.neighbors import KNeighborsClassifier
range_k = range(1,15)
scores = {}
scores_list = []
#xtrain = xtrain.reshape(-1, 1)
#ytrain = ytrain.reshape(-1, 1)
for k in range_k:
   classifier = KNeighborsClassifier(n_neighbors=k)
   classifier.fit(xtrain.astype(int).reval(), ytrain.astype(int))
   y_pred = classifier.predict(xtest)
   #scores[k] = metrics.accuracy_score(ytest,y_pred)
   #scores_list.append(metrics.accuracy_score(ytest,y_pred))
result = metrics.confusion_matrix(ytest, y_pred)

AttributeError: 'numpy.ndarray' object has no attribute 'reval'

In [275]:
y = data[["fare_amount"]]
x = data[['distance', 'pickup_time']]

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 0)
OvO_clf = OneVsOneClassifier(LogisticRegression(solver='lbfgs', max_iter=100))
OvO_clf.fit(xtrain[:50].astype(int), ytrain[:50].astype(int))

y_pred = OvO_clf.predict(xtest)

print('Accuracy of OvO Classifier: {:.2f}'.format(accuracy_score(ytest.astype(int), y_pred)))

C:\Users\brand\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


Accuracy of OvR Classifier: 0.10


In [276]:
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_val_score

lasso = linear_model.Lasso()
print(cross_val_score(lasso, x, y, cv=3))

[0.00055561 0.00139453 0.00094112]


In [ ]:
from statistics import mean, stdev
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold as skf
from sklearn import linear_model

x = data['distance']
y = data['fare_amount']

xdf = pd.DataFrame(data, columns=['distance'])
ydf = pd.DataFrame(data, columns=['fare_amount'])

xdf = df.to_numpy()
ydf = df.to_numpy()

xdf = xdf.reshape(-1, 1)
ydf = ydf.reshape(-1, 1)


scaler = preprocessing.MinMaxScaler()
x_scaled = scaler.fit_transform(xdf)

lr = linear_model.LogisticRegression()

skf = skf(n_splits=2)
for train_index, test_index in skf.split(xdf.astype(int), ydf.astype(int)):
    x_train_fold, x_test_fold = x_scaled[train_index], x_scaled[test_index]
    y_train_fold, y_test_fold = ydf[train_index], ydf[test_index]
    lr.fit(x_train_fold.astype(int), y_train_fold.astype(int))
    lst_accu_stratified.append(lr.score(x_test_fold, y_test_fold))
  
print('List of possible accuracy:', lst_accu_stratified)
print('\nMaximum Accuracy That can be obtained from this model is:',
      max(lst_accu_stratified)*100, '%')
print('\nMinimum Accuracy:',
      min(lst_accu_stratified)*100, '%')
print('\nOverall Accuracy:',
      mean(lst_accu_stratified)*100, '%')
print('\nStandard Deviation is:', stdev(lst_accu_stratified))

C:\Users\brand\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\brand\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
